### ISSUE TITLE
nginx rules

### ISSUE THREAD

**Issue by Samanw** [rsm23/O.M.V-V2#1]
Hi
good job, could you create rules for nginx webserver?

**Comment by rsm23** [comment]
I'll try, because I've never worked with nginx webservers

**Comment by rsm23** [comment]
Saif Rahmani has sent you a message via Indiegogo Life about the Help me to fund my self and my education fundraiser.

Hi,

I'm reaching out to ask for your support for my online fundraiser: "Help me to fund my self and my education."

There are two ways to help:
1. Donate - even small donations raise our popularity and give us more visibility on the site.
2. Post to Facebook - in the end, the more people hear about us, the more likely we are to meet our target.

Indiegogo Life has no fees, so anything we raise goes directly to our goal.

Thank you!

Saif Rahmani

Help the "Help me to fund my self and my education" fundraiser reach its goal today!
